apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: abrhman/flaskapp:beta
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "500m" # This limits the container to 50% of a CPU core
              memory: "256Mi" # This limits the container to 256MB of memory
            requests:
              cpu: "250m" # This reserves 25% of a CPU core for the container
              memory: "128Mi" # This reserves 128MB of memory for the container

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: _{_EXTERNAL_IP_}_
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-app-service
            port:
              number: 80
