name: Generate ASCII Artwork

on:
    push

jobs:
   ascii_job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repoo
          uses: actions/checkout@v4

        - name: List Repo Files
          run: ls -ltr
        
        - name: Exec Shell Script
          run: |
           chmod +x ascii-script.sh
           ./ascii-script.sh
