name: Generate ASCII Artwork

on:
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay Progrm
              run: sudo apt-get install cowsay -y
            
            - name: Exec Cowsay CMD
              run: cowsay -f dragon "Run for cover :), I am DRAGON" >> dargon.txt

            - name: Upload Dragon text file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dargon.txt
    
    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
          - name: Download Dragon text file
            uses: actions/download-artifact@v4
            with:
                name: dragon-text-file
    
          - name: Test File Exits 
            run: grep -i "dargon" dragon.txt


    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
          - name: Download Dragon text file
            uses: actions/download-artifact@v4
            with:
               name: dragon-text-file             

          - name: Read File
            run: cat dragon.txt  
 
          - name: Deploy
            run: echo Deploying ... .. . .  



#    ascii_job:
#     runs-on: ubuntu-latest
#     steps:
#         - name: Checkout Repoo
#           uses: actions/checkout@v4

#         - name: List Repo Files
#           run: ls -ltr
        
#         - name: Exec Shell Script
#           run: |
#            chmod +x ascii-script.sh
#            ./ascii-script.sh
        