name: Test Kubernetes Commands

on:
  push:
    branches:
      - main

jobs:
  test-k8s:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl CLI
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.0'

    - name: Set Kubeconfig file
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.KUBECONFIG}}

    - name: Test Kubernetes Connection
      run: |
        kubectl version 
        echo --------------------------------------------------------
        kubectl get nodes

