name: Trigger workflow with Varios Inputs

on:
    workflow_dispatch: 
        inputs:
            run-tests:
                description: "Run tests?"
                type: boolean
                required: true
            test-type:
                description: "Typr of tests to run"
                type: choice
                options:
                    - unit
                    - integration
                    - all
                required: true
            environment:
                description: "Choose an environment"
                required: true
                type: environment
            build-number:
                description: "Custom build number"
                type: number
                required: true
            message:
                description: "Additional message"
                type: string
                required: true


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Get inputs from workflow_dispatch
            - name: Print workflow inputs
              run: |
                echo "Run Tests: ${{inputs.run-tests}}"
                echo "Test type: ${{inputs.test-type}}"
                echo "Environment: ${{inputs.environment}}"
                echo "Build number: ${{inputs.build-number}}"
                echo "Message: ${{inputs.message}}"
            
            # Perform actions based on inputs
            - name: Run tests (if selected)
              if: ${{inputs.run-tests}} == true
              run: echo "Testing ... .. .. ."
       
            # Deploy to chosen environment
            # - name: Deploy to ${{inputs.environment}}
            #   environment: ${{inputs.environment}}