name: Test var and secrets

on:
    #[ workflow_dispatch ] will make able to run this Workflow manually 
    workflow_dispatch: 
    push: 

env:
    CONTAINER_REGISTRY: imagetestpush
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:

        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

            - name: Docker Login
              run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_USERNAME}}

            - name: Docker Publish
              run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
    
    deploy:
        if: github.ref == 'refs/heads/main'
        needs: docker
        runs-on: ubuntu-latest
        concurrency: 
          group: production-deployment
          # if it is [[TRUE]] the and you run the workflow again that workflow still runnig this job will canceled 
          # & if it is [[FALSE]] and you try to run another workflow the first one will get into waiting state until the second one completed
          cancel-in-progress: true
        steps:
            - name: Docker Run
            # Terminate this step if it goes for more than 1 minute
              timeout-minutes: 1
              run: | 
               echo docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
               sleep 1000s