name: Workflow Filters and Activities

on:
    workflow_dispatch: 
    push: 
        # branches-ignore: 
        #     - feature/*
        #     - test/**
        branches: 
            - main
            - '!feature/*' # ignoring pushing to any branch name with feature using !
        
    pull_request: 
        types: 
            - opened
            - closed
        paths-ignore:  # workflow will only run whaen a pull request that includes a change on any file other than README.md
            - README.md
        branches:  # configures your workflow to only run on pull requests that target specific branches 
            - main
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflow/job/step is executed for event type - ${{github.event_name}}